name: GitHub Classroom Workflow

on: [push]

env:
  REGISTRY: ghcr.io

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/csce313-fa23-kebo/grading-pa1:release
      credentials:
        username: sairamanareddy
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1